/**/admittance_rcm_control:
  ros__parameters:
    base_link: "link_0"
    end_effector_link: "link_ee"
    f_ext_th: [4.0, 4.0, 4.0, 1.0, 1.0, 1.0]
    dq_gains: [1., 1., 1., 1., 1., 1., 1.]
    dx_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    exp_smooth: 0.95
