# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - kuka_green/joint_trajectory_controller

  kuka_green/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - kuka_green_A1
      - kuka_green_A2
      - kuka_green_A3
      - kuka_green_A4
      - kuka_green_A5
      - kuka_green_A6
      - kuka_green_A7