# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  A1:
    has_velocity_limits: true
    max_velocity: 1.4835298641951802
    has_acceleration_limits: true
    max_acceleration: 10.0
  A2:
    has_velocity_limits: true
    max_velocity: 1.4835298641951802
    has_acceleration_limits: true
    max_acceleration: 10.0
  A3:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: true
    max_acceleration: 10.0
  A4:
    has_velocity_limits: true
    max_velocity: 1.3089969389957472
    has_acceleration_limits: true
    max_acceleration: 10.0
  A5:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: true
    max_acceleration: 10.0
  A6:
    has_velocity_limits: true
    max_velocity: 2.3561944901923448
    has_acceleration_limits: true
    max_acceleration: 10.0
  A7:
    has_velocity_limits: true
    max_velocity: 2.3561944901923448
    has_acceleration_limits: true
    max_acceleration: 10.0